#!/bin/bash
docker run --rm=true -t -i -u="developer" --name webmachine -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK -v $(pwd)/../:/workspace/base  webmachine $1
